<?php

/**
 * implements hook_site_info_theme_suggestions_block_alter()
 * Add a new twig theme suggestion for this block type
 */
function ucb2021_base_site_info_theme_suggestions_block_alter(&$suggestions, $variables) {
  $content = $variables['elements']['content'];
  if (isset($content['#block_content']) && $content['#block_content'] instanceof \Drupal\block_content\BlockContentInterface) {
    $suggestions[] = 'block__' . $content['#block_content']->bundle();
  }
}