name: Lint Code
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint_css:
    name: Run CSS linter
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Lint code
        run: npm run stylelint
  lint_js:
    name: Run JS linter
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Lint code
        run: npm run eslint
